# Generated by Django 5.0.14 on 2026-06-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
